import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/widgets/Header";
import Footer from "@/widgets/Footer/ui/Footer";
import StoreProvider from "@/store/storeProvider";
import {SessionProviderClient} from "@/app/SessionProvider";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "TechStore",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <SessionProviderClient>
      <StoreProvider>
          <Header/>
          {children}
          <Footer/>
      </StoreProvider>
      </SessionProviderClient>
      </body>
    </html>
  );
}
