import type { Metadata } from "next";
//import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import NavigationInPaymentPages from "@/widgets/navigationInPaymentPages/ui/NavigationInPaymentPages";
// const geistSans = Geist({
//     variable: "--font-geist-sans",
//     subsets: ["latin"],
// });
//
// const geistMono = Geist_Mono({
//     variable: "--font-geist-mono",
//     subsets: ["latin"],
// });

export const metadata: Metadata = {
    title: "TechStore",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
       <>
           <NavigationInPaymentPages/>
           {children}
       </>
    );
}